# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: endpoint
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: https://github.com/aesedeu/argotest.git
#     targetRevision: HEAD
#     path: dev
#   destination: 
#     server: https://kubernetes.default.svc
#     namespace: test

#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true

#     automated:
#       selfHeal: true
#       prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: test
spec:
  project: default

  source:
    repoURL: https://github.com/aesedeu/argotest.git
    targetRevision: HEAD
    path: dev2
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true